version: '3.2'
services:
  server:
    container_name: "admin-server-${SOURCE_COMMIT}"
    image: "${DOCKER_REPO}:${SOURCE_COMMIT}"
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "$API_HOST_PORT:8080"
    environment:
      SERVER_PORT: 8080
